name: invest
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scipy
  - statsmodels
  - jupyterlab
  - ipykernel
  - pip:
      - quantstats
      - pyportfolioopt

