version: 1
data:
  source: stooq                        # price history source (stooq, synthetic)
  price_source: stooq                  # override to yfinance for Yahoo pricing
  metadata_source: fmp                 # options: fmp, yfinance
  fundamentals_source: fmp             # options: fmp, yfinance
  api_keys:
    fmp: "NC03SC7kceZU55sPMw0H79Ih1QzftScM"        # replace with your Financial Modeling Prep key
  use_yfinance: false                  # keep available as a fallback path
  fmp:
    batch_size: 100                    # max tickers per call (comma-delimited)
    call_delay: 6.0                    # seconds between calls (free tier ~5/min)
    max_retries: 3
    timeout: 30.0
  yfinance_chunk_size: 20              # optional rate-limit controls (default 50)
  yfinance_call_delay: 0.6            # seconds sleep between chunks
  yfinance_max_retries: 5              # retry attempts when rate limited
  yfinance_retry_backoff: 2.0          # exponential backoff factor for retries
  cache:
    enabled: true
    dir: data/cache
    expiry_days: 3
  stockrover_file: /Users/harryzhang/Library/CloudStorage/Dropbox/investment/data/universe/universe.txt   # StockRover export that defines the investable universe
  universe: []                      # legacy fallback if no file is provided
  start: 2018-01-01
  end: null
  benchmark: SPY.US

portfolio:
  mode: buffet

  # asset count constraints
  min_count: 5
  max_count: 15
  target_count: 10

  # selection method before optimization
  selection:
    method: none          # options: top_by_1y_return, top_by_sharpe, none
    lookback_days: 252

  # optimization objective and parameters
  optimization:
    model: mean_variance           # options: mean_variance, black_litterman, risk_parity, equal_weight
    frequency: 252
    risk_free_rate: 0.0
    long_only: true
    leverage: 1.0
    weight_bounds: [0.0, 0.35]
    guardrails:
      max_volatility: 0.18
      min_return: 0.05
    black_litterman:
      tau: 0.05                    # shrinkage applied to the prior covariance
      risk_aversion: 2.5           # equilibrium risk aversion used for posterior weights
      market_caps: {}              # optional: {AAPL.US: 2.7e12, MSFT.US: 2.5e12}
      absolute_views: {}           # optional: {NVDA.US: 0.15, META.US: 0.10}
    risk_parity:
      method: inverse_volatility   # placeholder for future extensions

  # concentration rules (applied only if mode=buffet)
  concentration:
    enforce: false  # true or false
    top_k: 5
    top_k_min_share: 0.50

  # optional backtesting block for optimisation output
  backtest:
    enabled: true            # true or false
    method: walk_forward             # options: in_sample, walk_forward
    rebalance_freq: Q             # M=monthly, Q=quarterly, A=annual
    train_years: 5
    test_years: 1
    transaction_cost_bps: 5
    risk_free_rate: 0.0

execution:
  rebalance: none
  fee_rate: 0.0000

reporting:
  output_dir: output
  export_extras: true
  title: "Static Portfolio Allocation Report"
  var_alpha: 0.95

notes:
  - "Run with: python portfolio_agent/run.py [optional_config_path]."
  - "Update data.stockrover_file to point at the latest StockRover export."
  - "All analysis is for educational purposes only."
